blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blog_list/', views.blog_list, name='blog_list'), 
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),

    path('create_blog/', views.create_blog, name='create_blog'),
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    
    path('save_favorite/', views.favorite_blogs, name='favorite_blogs'),
    path('blog/save_favorite/<int:blog_id>/', views.save_favorite, name='save_favorite'),
    
    path('author_profile/<int:author_id>/', views.view_author_profile, name='view_author_profile'),
    path('search_blogs/', views.blog_search, name='blog_search'),
    
    path('category/<int:category_id>/', views.blog_by_category, name='blog_by_category'),
    
    path('leave_review/<int:blog_id>/', views.leave_review, name='leave_review'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')), 
    path('blog/', include('blog.urls')), 
] 

blog/models.py
from django.db import models
from accounts.models import CustomUser 

class BlogCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  

    def __str__(self):
        return self.title

class BlogReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  
    blog_post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(7)])
    review_text = models.TextField()

    def __str__(self):
        return f"Review by {self.user.username} on {self.blog_post.title}"


class Favorite(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  
    blog_post = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s favorite: {self.blog_post.title}"

blog/forms.py
from django import forms
from .models import Blog, BlogReview 

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'category']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = BlogReview  
        fields = ['rating', 'review_text']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Blog, BlogReview, BlogCategory, Favorite
from .forms import BlogForm, ReviewForm 
from django.contrib.auth.models import User 
from django.db.models import Avg
from django.db.models import Q
from django.contrib import messages


@login_required
def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            category_id = request.POST.get('category')
            new_category_name = request.POST.get('new_category')

            if category_id:
                category = BlogCategory.objects.get(pk=category_id)
            elif new_category_name:
                category, created = BlogCategory.objects.get_or_create(name=new_category_name)

            if category:
                blog = form.save(commit=False)
                blog.author = request.user
                blog.category = category
                blog.save()
                return redirect('blog_list')  
    else:
        form = BlogForm()
    categories = BlogCategory.objects.all()
    return render(request, 'blog/create_blog.html', {'form': form, 'categories': categories})


@login_required
def edit_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id, author=request.user)
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('blog_list') 
    else:
        form = BlogForm(instance=blog)
    return render(request, 'blog/edit_blog.html', {'form': form, 'blog': blog})

@login_required
def delete_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id, author=request.user)
    if request.method == 'POST':
        blog.delete()
        return redirect('blog_list')  
    return render(request, 'blog/delete_blog.html', {'blog': blog})

@login_required
def save_favorite(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    user = request.user

    if not Favorite.objects.filter(user=user, blog_post=blog).exists():
        Favorite.objects.create(user=user, blog_post=blog)
        messages.success(request, "Blog added to favorites.")
    else:
        messages.warning(request, "Blog already in favorites.")
    return redirect('blog_detail', blog_id=blog_id) 



@login_required
def favorite_blogs(request):
    user = request.user
    favorite_blogs = Favorite.objects.filter(user=user).values('blog_post')
    blogs = Blog.objects.filter(id__in=favorite_blogs)

    context = {
        'blogs': blogs,
    }
    return render(request, 'blog/favorite_blogs.html', context)






def view_author_profile(request, author_id):
    author = get_object_or_404(User, id=author_id)
    author_blogs = Blog.objects.filter(author=author)
    return render(request, 'blog/author_profile.html', {'author': author, 'author_blogs': author_blogs})



def blog_search(request):
    query = request.GET.get('q')
    if query:
        blogs = Blog.objects.filter(title__icontains=query)
    else:
        blogs = Blog.objects.none()
    return render(request, 'blog/blog_search_results.html', {'query': query, 'blogs': blogs})


def leave_review(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    reviews = BlogReview.objects.filter(blog_post=blog)
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.blog_post = blog
            review.save()
            return redirect('blog_detail', blog_id=blog_id)
    else:
        form = ReviewForm()
    average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
    return render(request, 'blog/leave_review.html', {'form': form, 'blog': blog, 'reviews': reviews, 'average_rating': average_rating})



@login_required
def blog_list(request):
    blogs = Blog.objects.annotate(avg_rating=Avg('blogreview__rating'))
    context = {
        'blogs': blogs,
    }
    return render(request, 'blog/blog_list.html', context)


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blog/blog_detail.html', {'blog': blog})

#filter blog
def blog_by_category(request):
    blogs = Blog.objects.annotate(avg_rating=Avg('blogreview__rating'))
    if request.GET.get('category_id'):
        blogs = blogs.filter(category_id=request.GET.get('category_id'))
        selected_category = BlogCategory.objects.get(id=request.GET.get('category_id'))
    else:
        blogs = []
        selected_category = None
    context = {
        'blogs': blogs,
        'selected_category': selected_category,
        'categories': BlogCategory.objects.all(),
    }
    return render(request, 'blog/category_filtered_blogs.html', context)

blog/templates/blog/author_profile.html
{% extends 'base.html' %}
{% block content %}
  <h2>Author Profile</h2>
  <p>Author: {{ author.username }}</p>
  
  <h3>Articles by {{ author.username }}</h3>
  <ul>
    {% for blog in author_blogs %}
      <li><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">{{ blog.title }}</h2>
                    <p class="card-text">{{ blog.body }}</p>
                    <h6 class="card-text">Category: {{ blog.category.name }}</h6>
                    <h6 class="card-text">Author: {{ blog.author.username }}</h6>
                    <h6 class="card-text">Published on: {{ blog.date|date:"F d, Y" }}</h6>


                    <h5>Reviews:</h5>
                    {% if blog.blogreview_set.all %}
                        <ul>
                            {% for review in blog.blogreview_set.all %}
                                <li>
                                    <strong>Rating:</strong> {{ review.rating }}<br>
                                    <strong>Review:</strong> {{ review.review_text }}<br>
                                    <strong>By:</strong> {{ review.user.username }}<br>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>No reviews yet.</p>
                    {% endif %}
                    
                    <a href="{% url 'leave_review' blog_id=blog.id %}" class="btn btn-primary">Add Review</a>

                    {% if user.is_authenticated and user == blog.author %}
                    <a style=" margin-top: 5px;" href="{% url 'edit_blog' blog.id %}" class="btn btn-primary">Edit</a>
                    <a style=" margin-top: 5px;" href="{% url 'delete_blog' blog.id %}" class="btn btn-danger">Delete</a>                
                    {% endif %}

                    <form style=" margin-top: 5px;" method="post" action="{% url 'save_favorite' blog.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Save as Favorite</button>
                    </form>

                    <a style=" margin-top: 5px;" href="{% url 'blog_list' %}" class="btn btn-secondary">Back to Blog List</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Morning Diary</title>
    <!-- Add Bootstrap CSS link here -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Add your custom CSS link here if needed -->
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">The Morning Diary</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/blog_list">Blog</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/blog/create_blog/">Create Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/profile/">Profile</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/login/">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/register/">Register</a>
                </li>
            {% endif %}
        </ul>
  
        <!-- Search Bar -->
        <form class="form-inline my-2 my-lg-0" action="{% url 'blog_search' %}" method="get">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav> 

   <div style = "text-align: center;" class="card-footer ">  
    <h1 style = "text-align: center; color: orange;  margin-top: 18px;" >Blog List</h1>
    <ul>
        {% for blog in blogs %}  
                <h2 style = "margin-top: 40px; text-align: center;" ><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></h2>
                <p>{{ blog.body }}</p>

                <div style = "text-align: center;" class="card-footer text-muted">  
                <p>Author: {{ blog.author }} | Category: {{ blog.category }} | Date: {{ blog.date }} | Average Rating: {{ blog.avg_rating|default:"N/A" }}</p>
                </div>
        {% endfor %}
      </ul>
    </div>
 </body>
</html>

blog/templates/blog/blog_search_results.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search Results for "{{ query }}"</h2>
    <ul>
        {% for blog in blogs %}
            <li><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></li>
        {% empty %}
            <li>No results found.</li>
        {% endfor %}
    </ul>
{% endblock %}

blog/templates/blog/category_filtered_blogs.html
{% extends 'base.html' %}

{% block content %}
  <h1>Blogs in Category: {{ selected_category.name }}</h1>

  {% for blog in blogs %}
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">{{ blog.title }}</h5>
      </div>
      <div class="card-body">
        <p class="card-text">{{ blog.body }}</p>
        <p>Author: {{ blog.author }}</p>
        
      </div>
    </div>
  {% empty %}
    <p>No blogs in this category yet.</p>
  {% endfor %}
{% endblock %}

blog/templates/blog/create_blog.html
{% extends 'base.html' %}
{% block content %}
  <div style="align-items: center; text-align: center;" class="container">
    <div class="d-flex justify-content-center">
      <h2 class="text-center" style="font-size: 2.5rem; color: #007bff; margin-top: 20px;">Create a New Blog Post</h2>
    </div>
    <form method="post" style="max-width: 500px; margin: 0 auto;">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.title.id_for_label }}" style="font-size: 1.2rem; color: #333;">Title</label>
        {{ form.title }}
      </div>
      <div class="form-group">
        <label for="{{ form.body.id_for_label }}" style="font-size: 1.2rem; color: #333;">Body</label>
        {{ form.body }}
      </div>
      <div class="form-group">
        <label for="{{ form.category.id_for_label }}" style="font-size: 1.2rem; color: #333;">Category</label>
        {{ form.category }}
      </div>
      <button type="submit" class="btn btn-primary mt-3" style="background-color: #007bff;">Create</button>
    </form>
    <a style="margin-top: 20px; display: block; text-align: center; font-size: 1.2rem; text-white;" href="{% url 'blog_list' %}" class="btn btn-primary mt-3">Back to Blog List</a>
  </div>
{% endblock %}

blog/templates/blog/delete_blog.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete Blog Post</h2>
  <p>Are you sure you want to delete "{{ blog.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a href="{% url 'blog_list' %}">Cancel</a>
{% endblock %}

blog/templates/blog/edit_blog.html
{% extends 'base.html' %}
{% block content %}
  <h2>Edit Blog Post</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
  <a href="{% url 'blog_list' %}">Back to Blog List</a>
{% endblock %}

blog/templates/blog/favorite_blogs.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align:center;">Your favorite blogs</h3>
  <ul>
    {% for blog in blogs %}
      <li><a href="{% url 'blog_detail' blog_id=blog.id %}">{{ blog.title }}</a></li>
    {% empty %}
      <li>No favorite blogs yet.</li>
    {% endfor %}
  </ul>
{% endblock %}

blog/templates/blog/leave_review.html
{% extends 'base.html' %}
{% block content %}
  <h2>Leave a Review for "{{ blog.title }}"</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.rating.label_tag }}<br>
      {{ form.rating }}
    </div>
    <div class="form-group">
      {{ form.review_text.label_tag }}<br>
      {{ form.review_text }}
    </div>
    <button type="submit">Submit Review</button>
  </form>
  <a href="{% url 'blog_detail' blog_id=blog.id %}">Back to Blog Post</a>
{% endblock %}